// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1cEpNoMEI8DNMcu_bJHZAiL9KjkG2Mb0',
    appId: '1:67170666079:web:0500849cf69a6012e4fdea',
    messagingSenderId: '67170666079',
    projectId: 'flutterlogin-2c3cd',
    authDomain: 'flutterlogin-2c3cd.firebaseapp.com',
    storageBucket: 'flutterlogin-2c3cd.appspot.com',
    measurementId: 'G-19ST4NLYBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASwlIfkUzaipEsgtKH7yLcyk9qmpZyeSw',
    appId: '1:67170666079:android:bb2f3860d360c850e4fdea',
    messagingSenderId: '67170666079',
    projectId: 'flutterlogin-2c3cd',
    storageBucket: 'flutterlogin-2c3cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEZ27fCFP-T2HwxvNsYBZeT797sphklx0',
    appId: '1:67170666079:ios:5228c63c9c01ec59e4fdea',
    messagingSenderId: '67170666079',
    projectId: 'flutterlogin-2c3cd',
    storageBucket: 'flutterlogin-2c3cd.appspot.com',
    iosClientId: '67170666079-nih7dqqoain6o1ra7l03jj1e92i5c7h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEZ27fCFP-T2HwxvNsYBZeT797sphklx0',
    appId: '1:67170666079:ios:5228c63c9c01ec59e4fdea',
    messagingSenderId: '67170666079',
    projectId: 'flutterlogin-2c3cd',
    storageBucket: 'flutterlogin-2c3cd.appspot.com',
    iosClientId: '67170666079-nih7dqqoain6o1ra7l03jj1e92i5c7h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}